jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test with Maven
      run: mvn test -B --file pom.xml
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        os:
        - ubuntu-20.04
        - macOS-latest
        - windows-latest
      max-parallel: 2
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
